In [1]:
import numpy as np
import pandas as pd

In [2]:
url = "https://raw.githubusercontent.com/deristnoor/python/refs/heads/master/project/Data%20Science%20%26%20Machine%20Learning/Melting%20Points/data/train.csv"
df = pd.read_csv(url, index_col="id")
df.head()

,SMILES,Tm,Group 1,Group 2,Group 3,Group 4,Group 5,Group 6,Group 7,Group 8,...,Group 415,Group 416,Group 417,Group 418,Group 419,Group 420,Group 421,Group 422,Group 423,Group 424
id,,,,,,,,,,,,,,,,,,,,,
2175,FC1=C(F)C(F)(F)C1(F)F,213.15,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1222,c1ccc2c(c1)ccc3Nc4ccccc4c23,407.15,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2994,CCN1C(C)=Nc2ccccc12,324.15,2,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1704,CC#CC(=O)O,351.15,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2526,CCCCC(S)C,126.15,2,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
df.index.value_counts().sort_values(ascending=False)

id
2175    1
1222    1
2994    1
1704    1
2526    1
       ..
707     1
1573    1
1634    1
3022    1
1673    1
Name: count, Length: 2662, dtype: int64

In [5]:
df.describe()

,Tm,Group 1,Group 2,Group 3,Group 4,Group 5,Group 6,Group 7,Group 8,Group 9,...,Group 415,Group 416,Group 417,Group 418,Group 419,Group 420,Group 421,Group 422,Group 423,Group 424
count,2662.000000,2662.000000,2662.000000,2662.000000,2662.000000,2662.000000,2662.000000,2662.000000,2662.000000,2662.000000,...,2662.000000,2662.000000,2662.0,2662.000000,2662.0,2662.0,2662.0,2662.0,2662.0,2662.0
mean,278.263452,1.020661,1.582269,0.114951,0.036439,0.036814,0.022915,0.013524,0.010143,0.007137,...,0.001127,0.000751,0.0,0.001878,0.0,0.0,0.0,0.0,0.0,0.0
std,85.117914,1.353640,3.738416,0.425964,0.208307,0.205516,0.164037,0.118732,0.117480,0.092695,...,0.033558,0.027405,0.0,0.058126,0.0,0.0,0.0,0.0,0.0,0.0
min,53.540000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
25%,217.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
50%,277.300000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
75%,325.150000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
max,897.150000,16.000000,42.000000,6.000000,3.000000,2.000000,2.000000,2.000000,2.000000,2.000000,...,1.000000,1.000000,0.0,2.000000,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
df.dtypes

SMILES        object
Tm           float64
Group 1        int64
Group 2        int64
Group 3        int64
              ...
Group 420      int64
Group 421      int64
Group 422      int64
Group 423      int64
Group 424      int64
Length: 426, dtype: object

In [7]:
X = df.drop(['SMILES', 'Tm'], axis=1)
X.head()

,Group 1,Group 2,Group 3,Group 4,Group 5,Group 6,Group 7,Group 8,Group 9,Group 10,...,Group 415,Group 416,Group 417,Group 418,Group 419,Group 420,Group 421,Group 422,Group 423,Group 424
id,,,,,,,,,,,,,,,,,,,,,
2175,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1222,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2994,2,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1704,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2526,2,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
y = df.Tm
y.head()

id
2175    213.15
1222    407.15
2994    324.15
1704    351.15
2526    126.15
Name: Tm, dtype: float64

In [10]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    # stratify=y,
    test_size=0.2,
    random_state=0
)

In [14]:
from sklearn.linear_model import LinearRegression, HuberRegressor
from xgboost.sklearn import XGBRegressor
from sklearn.metrics import mean_absolute_error

import warnings
warnings.filterwarnings('ignore')

classifiers = [
    "LinearRegression", 
    "HuberRegressor", 
    "XGBRegressor"
]

models = [
    LinearRegression(),
    HuberRegressor(), 
    XGBRegressor(random_state=0)
]

In [15]:
Score = pd.DataFrame({"Regressor":classifiers})
j = 0
mae = []
for i in models:
    model = i
    model.fit(X_train,y_train)
    predictions = model.predict(X_test)
    mae.append(mean_absolute_error(y_test,predictions))
    j = j+1     

Score["MAE"] = mae
Score.sort_values(by="MAE", ascending=False,inplace = True)
Score.reset_index(drop=True, inplace=True)
Score

          Regressor        MAE
0  LinearRegression  36.859814
1    HuberRegressor  36.626551
2      XGBRegressor  36.019691

In [16]:
from sklearn.model_selection import GridSearchCV, StratifiedKFold

In [47]:
model_fix = XGBRegressor(gamma=0, min_child_weight=1, n_estimators=1200, random_state=0)

In [48]:
params = {
    "learning_rate": [0.01, 0.05, 0.1],
    "max_depth": [3, 5, 7, 9],
    "subsample": [0.6, 0.7, 0.8, 0.9],
    "colsample_bytree": [0.6, 0.7, 0.8, 0.9],
    # "reg_alpha": [0, 0.1, 0.5, 1],
    # "reg_lambda": [0.5, 1, 2, 3, 4]
}

skfold = StratifiedKFold(n_splits=5)

grid_search = GridSearchCV(
    estimator=model_fix,
    param_grid=params,
    cv=5,
    scoring='neg_mean_absolute_error',
    # verbose=1,
    n_jobs=-1,
)

In [62]:
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=XGBRegressor(base_score=None, booster=None,
                                    callbacks=None, colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None, device=None,
                                    early_stopping_rounds=None,
                                    enable_categorical=False, eval_metric=None,
                                    feature_types=None, feature_weights=None,
                                    gamma=0, grow_policy=None,
                                    importance_type=None,
                                    interaction_constraints=None,
                                    le...
                                    max_cat_to_onehot=None, max_delta_step=None,
                                    max_depth=None, max_leaves=None,
                                    min_child_weight=1, missing=nan,
                                    monotone_constraints=None,
                                    multi_strategy=None, n_estimators=1200,
                                    n_jobs=None, num_parallel_tree=None, ...),
             n_jobs=-1,
             param_grid={'colsample_bytree': [0.6, 0.7, 0.8, 0.9],
                         'learning_rate': [0.01, 0.05, 0.1],
                         'max_depth': [3, 5, 7, 9],
                         'subsample': [0.6, 0.7, 0.8, 0.9]},
             scoring='neg_mean_absolute_error')

In [31]:
print('Neg_MAE_score:', grid_search.best_score_)
print('Best Parameters:', grid_search.best_params_)

Neg_MAE_score: -36.59880198763573
Best Parameters: {'learning_rate': 0.1, 'max_depth': 7, 'n_estimators': 1200}

In [27]:
print('Neg_MAE_score:', grid_search.best_score_)
print('Best Parameters:', grid_search.best_params_)

Neg_MAE_score: -35.0539972119889
Best Parameters: {'gamma': 0, 'learning_rate': 0.1, 'max_depth': 5, 'min_child_weight': 1, 'n_estimators': 1200}

In [37]:
print('Neg_MAE_score:', grid_search.best_score_)
print('Best Parameters:', grid_search.best_params_)

Neg_MAE_score: -35.22701402165145
Best Parameters: {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 7, 'n_estimators': 1200, 'subsample': 0.6}

In [63]:
print('Neg_MAE_score:', grid_search.best_score_)
print('Best Parameters:', grid_search.best_params_)

Neg_MAE_score: -34.52276547369653
Best Parameters: {'colsample_bytree': 0.6, 'learning_rate': 0.1, 'max_depth': 5, 'subsample': 0.9}

In [64]:
model_try = XGBRegressor(
    # tree_method='hist',
    learning_rate=0.1,
    max_depth=5,
    gamma=0,
    min_child_weight=1, 
    n_estimators=1200,
    colsample_bytree=0.6,
    subsample=0.9, 
    random_state=0
)
model_try.fit(X_train, y_train)
predictions = model_try.predict(X_test)
score = mean_absolute_error(y_test,predictions)
score

33.78889115381867